#include <vector>
#include <map>
#include <set>
#include <functional>
#include "production.hpp"
using namespace std; 
enum NTSYMBOL {
AEXPR, ARGSLIST, BLESSEXPR, BLOCKSTMT, COMPEXPR, DECLLIST, 
DECLSTMT, DEFSTMT, EXPLIST, EXPR, EXPSTMT, 
FACT, IFSTMT, LAMBDAEXPR, LETSTMT, LISTCON, 
PARAMLIST, POST, PRI, PRINTSTMT, PROG, 
RELEXPR, RETSTMT, STMT, STMTLIST, STRUCTSTMT, 
TERM, WHILESTMT, sp
};
map<int, Production> prod;
void initprod() {
	 prod[1]  = Production(1,"sp", SymbolString({"PROG"}),"");
	 prod[2]  = Production(2,"PROG", SymbolString({"STMTLIST"}),"");
	 prod[3]  = Production(3,"STMTLIST", SymbolString({"STMT","STMTLIST"}),"@mkList");
	 prod[4]  = Production(4,"STMTLIST", SymbolString({"STMT"}),"");
	 prod[5]  = Production(5,"STMT", SymbolString({"EXPSTMT"}),"");
	 prod[6]  = Production(6,"STMT", SymbolString({"IFSTMT"}),"");
	 prod[7]  = Production(7,"STMT", SymbolString({"WHILESTMT"}),"");
	 prod[8]  = Production(8,"STMT", SymbolString({"BLOCKSTMT"}),"");
	 prod[9]  = Production(9,"STMT", SymbolString({"PRINTSTMT"}),"");
	 prod[10]  = Production(10,"STMT", SymbolString({"LETSTMT"}),"");
	 prod[11]  = Production(11,"STMT", SymbolString({"DEFSTMT"}),"");
	 prod[12]  = Production(12,"STMT", SymbolString({"RETSTMT"}),"");
	 prod[13]  = Production(13,"STMT", SymbolString({"STRUCTSTMT"}),"");
	 prod[14]  = Production(14,"PARAMLIST", SymbolString({"DECLLIST"}),"");
	 prod[15]  = Production(15,"PARAMLIST", SymbolString(),"");
	 prod[16]  = Production(16,"DECLSTMT", SymbolString({"TK_LET","TK_ID"}),"@mkLet");
	 prod[17]  = Production(17,"DECLLIST", SymbolString({"DECLSTMT","TK_COMMA","DECLLIST"}),"@mkList");
	 prod[18]  = Production(18,"DECLLIST", SymbolString({"DECLSTMT"}),"");
	 prod[19]  = Production(19,"LETSTMT", SymbolString({"TK_LET","AEXPR","TK_SEMI"}),"@mkLet");
	 prod[20]  = Production(20,"PRINTSTMT", SymbolString({"TK_PRINT","AEXPR","TK_SEMI"}),"@mkPrint");
	 prod[21]  = Production(21,"PRINTSTMT", SymbolString({"TK_PRINTLN","AEXPR","TK_SEMI"}),"@mkPrint");
	 prod[22]  = Production(22,"BLOCKSTMT", SymbolString({"TK_LCURLY","STMTLIST","TK_RCURLY"}),"@mkBlock");
	 prod[23]  = Production(23,"IFSTMT", SymbolString({"TK_IF","TK_LPAREN","AEXPR","TK_RPAREN","BLOCKSTMT"}),"@mkIf");
	 prod[24]  = Production(24,"WHILESTMT", SymbolString({"TK_WHILE","TK_LPAREN","AEXPR","TK_RPAREN","BLOCKSTMT"}),"@mkWhile");
	 prod[25]  = Production(25,"DEFSTMT", SymbolString({"TK_FN","TK_ID","TK_LPAREN","PARAMLIST","TK_RPAREN","BLOCKSTMT"}),"@mkFunc");
	 prod[26]  = Production(26,"STRUCTSTMT", SymbolString({"TK_CLASS","TK_ID","BLOCKSTMT","TK_SEMI"}),"@mkStruct");
	 prod[27]  = Production(27,"RETSTMT", SymbolString({"TK_RETURN","AEXPR","TK_SEMI"}),"@mkRet");
	 prod[28]  = Production(28,"EXPSTMT", SymbolString({"AEXPR","TK_SEMI"}),"");
	 prod[29]  = Production(29,"AEXPR", SymbolString({"COMPEXPR","TK_ASSIGN","AEXPR"}),"@binop");
	 prod[30]  = Production(30,"AEXPR", SymbolString({"COMPEXPR","TK_ASSIGN_SUM","AEXPR"}),"@binop");
	 prod[31]  = Production(31,"AEXPR", SymbolString({"COMPEXPR","TK_ASSIGN_DIFF","AEXPR"}),"@binop");
	 prod[32]  = Production(32,"AEXPR", SymbolString({"COMPEXPR"}),"");
	 prod[33]  = Production(33,"COMPEXPR", SymbolString({"COMPEXPR","TK_EQU","RELEXPR"}),"@binop");
	 prod[34]  = Production(34,"COMPEXPR", SymbolString({"COMPEXPR","TK_NEQ","RELEXPR"}),"@binop");
	 prod[35]  = Production(35,"COMPEXPR", SymbolString({"RELEXPR"}),"");
	 prod[36]  = Production(36,"RELEXPR", SymbolString({"RELEXPR","TK_LT","EXPR"}),"@binop");
	 prod[37]  = Production(37,"RELEXPR", SymbolString({"RELEXPR","TK_GT","EXPR"}),"@binop");
	 prod[38]  = Production(38,"RELEXPR", SymbolString({"RELEXPR","TK_GTE","EXPR"}),"@binop");
	 prod[39]  = Production(39,"RELEXPR", SymbolString({"RELEXPR","TK_LTE","EXPR"}),"@binop");
	 prod[40]  = Production(40,"RELEXPR", SymbolString({"EXPR"}),"");
	 prod[41]  = Production(41,"EXPR", SymbolString({"EXPR","TK_ADD","TERM"}),"@binop");
	 prod[42]  = Production(42,"EXPR", SymbolString({"EXPR","TK_SUB","TERM"}),"@binop");
	 prod[43]  = Production(43,"EXPR", SymbolString({"TERM"}),"");
	 prod[44]  = Production(44,"TERM", SymbolString({"TERM","TK_MUL","FACT"}),"@binop");
	 prod[45]  = Production(45,"TERM", SymbolString({"TERM","TK_DIV","FACT"}),"@binop");
	 prod[46]  = Production(46,"TERM", SymbolString({"TERM","TK_MOD","FACT"}),"@binop");
	 prod[47]  = Production(47,"TERM", SymbolString({"FACT"}),"");
	 prod[48]  = Production(48,"FACT", SymbolString({"TK_SUB","POST"}),"@unary");
	 prod[49]  = Production(49,"FACT", SymbolString({"TK_NOT","POST"}),"@unary");
	 prod[50]  = Production(50,"FACT", SymbolString({"POST"}),"");
	 prod[51]  = Production(51,"POST", SymbolString({"POST","TK_LB","PRI","TK_RB"}),"@mkSubscript");
	 prod[52]  = Production(52,"POST", SymbolString({"POST","TK_LPAREN","ARGSLIST","TK_RPAREN"}),"@mkCall");
	 prod[53]  = Production(53,"POST", SymbolString({"POST","TK_PERIOD","PRI"}),"@mkDotted");
	 prod[54]  = Production(54,"POST", SymbolString({"POST","TK_DECREMENT"}),"@unary");
	 prod[55]  = Production(55,"POST", SymbolString({"POST","TK_INCREMENT"}),"@unary");
	 prod[56]  = Production(56,"POST", SymbolString({"PRI"}),"");
	 prod[57]  = Production(57,"PRI", SymbolString({"TK_LPAREN","AEXPR","TK_RPAREN"}),"@pass");
	 prod[58]  = Production(58,"PRI", SymbolString({"TK_NUM"}),"@mkNum");
	 prod[59]  = Production(59,"PRI", SymbolString({"TK_ID"}),"@mkId");
	 prod[60]  = Production(60,"PRI", SymbolString({"TK_STRING"}),"@mkString");
	 prod[61]  = Production(61,"PRI", SymbolString({"LISTCON"}),"");
	 prod[62]  = Production(62,"PRI", SymbolString({"BLESSEXPR"}),"");
	 prod[63]  = Production(63,"PRI", SymbolString({"LAMBDAEXPR"}),"");
	 prod[64]  = Production(64,"ARGSLIST", SymbolString({"EXPLIST"}),"");
	 prod[65]  = Production(65,"ARGSLIST", SymbolString(),"");
	 prod[66]  = Production(66,"EXPLIST", SymbolString({"COMPEXPR","TK_COMMA","EXPLIST"}),"@mkList");
	 prod[67]  = Production(67,"EXPLIST", SymbolString({"COMPEXPR"}),"");
	 prod[68]  = Production(68,"LISTCON", SymbolString({"TK_LB","ARGSLIST","TK_RB"}),"@mkListCon");
	 prod[69]  = Production(69,"BLESSEXPR", SymbolString({"TK_NEW","TK_ID","TK_LPAREN","ARGSLIST","TK_RPAREN"}),"@mkInstance");
	 prod[70]  = Production(70,"LAMBDAEXPR", SymbolString({"TK_LAMBDA","PARAMLIST","TK_RPAREN","TK_PRODUCE","STMT"}),"@mkLambda");
}
map<int,map<string,string>> goTab;
void initgoTab() {
	 goTab[0] = {{"AEXPR", "21"}, {"BLESSEXPR", "4"}, {"BLOCKSTMT", "12"}, {"COMPEXPR", "34"}, {"DEFSTMT", "9"}, {"EXPR", "27"}, {"EXPSTMT", "19"}, {"FACT", "24"}, {"IFSTMT", "18"}, {"LAMBDAEXPR", "32"}, {"LETSTMT", "8"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"PRINTSTMT", "10"}, {"PROG", "35"}, {"RELEXPR", "37"}, {"RETSTMT", "20"}, {"STMT", "13"}, {"STMTLIST", "22"}, {"STRUCTSTMT", "17"}, {"TERM", "33"}, {"WHILESTMT", "26"}};
	 goTab[1] = {{"DECLLIST", "43"}, {"DECLSTMT", "42"}, {"PARAMLIST", "45"}};
	 goTab[3] = {{"ARGSLIST", "47"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "49"}, {"EXPLIST", "48"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[11] = {{"BLESSEXPR", "4"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "50"}, {"PRI", "7"}};
	 goTab[13] = {{"AEXPR", "21"}, {"BLESSEXPR", "4"}, {"BLOCKSTMT", "12"}, {"COMPEXPR", "34"}, {"DEFSTMT", "9"}, {"EXPR", "27"}, {"EXPSTMT", "19"}, {"FACT", "24"}, {"IFSTMT", "18"}, {"LAMBDAEXPR", "32"}, {"LETSTMT", "8"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"PRINTSTMT", "10"}, {"RELEXPR", "37"}, {"RETSTMT", "20"}, {"STMT", "13"}, {"STMTLIST", "51"}, {"STRUCTSTMT", "17"}, {"TERM", "33"}, {"WHILESTMT", "26"}};
	 goTab[14] = {{"AEXPR", "52"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[16] = {{"AEXPR", "58"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[28] = {{"AEXPR", "21"}, {"BLESSEXPR", "4"}, {"BLOCKSTMT", "12"}, {"COMPEXPR", "34"}, {"DEFSTMT", "9"}, {"EXPR", "27"}, {"EXPSTMT", "19"}, {"FACT", "24"}, {"IFSTMT", "18"}, {"LAMBDAEXPR", "32"}, {"LETSTMT", "8"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"PRINTSTMT", "10"}, {"RELEXPR", "37"}, {"RETSTMT", "20"}, {"STMT", "13"}, {"STMTLIST", "63"}, {"STRUCTSTMT", "17"}, {"TERM", "33"}, {"WHILESTMT", "26"}};
	 goTab[29] = {{"AEXPR", "64"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[31] = {{"AEXPR", "66"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[40] = {{"AEXPR", "81"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[41] = {{"BLESSEXPR", "4"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "82"}, {"PRI", "7"}};
	 goTab[55] = {{"ARGSLIST", "90"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "49"}, {"EXPLIST", "48"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[56] = {{"BLESSEXPR", "4"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"PRI", "91"}};
	 goTab[57] = {{"BLESSEXPR", "4"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"PRI", "92"}};
	 goTab[60] = {{"AEXPR", "94"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[61] = {{"BLESSEXPR", "4"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"TERM", "95"}};
	 goTab[62] = {{"BLESSEXPR", "4"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"TERM", "96"}};
	 goTab[67] = {{"BLESSEXPR", "4"}, {"FACT", "101"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}};
	 goTab[68] = {{"BLESSEXPR", "4"}, {"FACT", "102"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}};
	 goTab[69] = {{"BLESSEXPR", "4"}, {"FACT", "103"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}};
	 goTab[70] = {{"BLESSEXPR", "4"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "104"}, {"TERM", "33"}};
	 goTab[71] = {{"AEXPR", "105"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[72] = {{"BLESSEXPR", "4"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "106"}, {"TERM", "33"}};
	 goTab[73] = {{"AEXPR", "107"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[74] = {{"AEXPR", "108"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[75] = {{"BLOCKSTMT", "109"}};
	 goTab[76] = {{"BLESSEXPR", "4"}, {"EXPR", "110"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"TERM", "33"}};
	 goTab[77] = {{"BLESSEXPR", "4"}, {"EXPR", "111"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"TERM", "33"}};
	 goTab[78] = {{"BLESSEXPR", "4"}, {"EXPR", "112"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"TERM", "33"}};
	 goTab[79] = {{"BLESSEXPR", "4"}, {"EXPR", "113"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"TERM", "33"}};
	 goTab[80] = {{"AEXPR", "114"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "34"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[83] = {{"DECLLIST", "116"}, {"DECLSTMT", "42"}};
	 goTab[86] = {{"ARGSLIST", "118"}, {"BLESSEXPR", "4"}, {"COMPEXPR", "49"}, {"EXPLIST", "48"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[88] = {{"BLESSEXPR", "4"}, {"COMPEXPR", "49"}, {"EXPLIST", "119"}, {"EXPR", "27"}, {"FACT", "24"}, {"LAMBDAEXPR", "32"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"RELEXPR", "37"}, {"TERM", "33"}};
	 goTab[99] = {{"DECLLIST", "43"}, {"DECLSTMT", "42"}, {"PARAMLIST", "123"}};
	 goTab[117] = {{"AEXPR", "21"}, {"BLESSEXPR", "4"}, {"BLOCKSTMT", "12"}, {"COMPEXPR", "34"}, {"DEFSTMT", "9"}, {"EXPR", "27"}, {"EXPSTMT", "19"}, {"FACT", "24"}, {"IFSTMT", "18"}, {"LAMBDAEXPR", "32"}, {"LETSTMT", "8"}, {"LISTCON", "5"}, {"POST", "15"}, {"PRI", "7"}, {"PRINTSTMT", "10"}, {"RELEXPR", "37"}, {"RETSTMT", "20"}, {"STMT", "126"}, {"STRUCTSTMT", "17"}, {"TERM", "33"}, {"WHILESTMT", "26"}};
	 goTab[122] = {{"BLOCKSTMT", "128"}};
	 goTab[125] = {{"BLOCKSTMT", "130"}};
	 goTab[129] = {{"BLOCKSTMT", "131"}};
}
map<int,map<string,string>> actTab;
void initactTab() {
	 actTab[0] = {{"TK_CLASS", "s36"}, {"TK_FN", "s30"}, {"TK_ID", "s38"}, {"TK_IF", "s25"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LCURLY", "s28"}, {"TK_LET", "s16"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_PRINT", "s40"}, {"TK_PRINTLN", "s14"}, {"TK_RETURN", "s31"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}, {"TK_WHILE", "s39"}};
	 actTab[1] = {{"TK_LET", "s44"}, {"TK_RPAREN", "r15"}};
	 actTab[2] = {{"TK_ID", "s46"}};
	 actTab[3] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_RB", "r65"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[4] = {{"TK_ADD", "r62"}, {"TK_ASSIGN", "r62"}, {"TK_ASSIGN_DIFF", "r62"}, {"TK_ASSIGN_SUM", "r62"}, {"TK_COMMA", "r62"}, {"TK_DECREMENT", "r62"}, {"TK_DIV", "r62"}, {"TK_EQU", "r62"}, {"TK_GT", "r62"}, {"TK_GTE", "r62"}, {"TK_INCREMENT", "r62"}, {"TK_LB", "r62"}, {"TK_LPAREN", "r62"}, {"TK_LT", "r62"}, {"TK_LTE", "r62"}, {"TK_MOD", "r62"}, {"TK_MUL", "r62"}, {"TK_NEQ", "r62"}, {"TK_PERIOD", "r62"}, {"TK_RB", "r62"}, {"TK_RPAREN", "r62"}, {"TK_SEMI", "r62"}, {"TK_SUB", "r62"}};
	 actTab[5] = {{"TK_ADD", "r61"}, {"TK_ASSIGN", "r61"}, {"TK_ASSIGN_DIFF", "r61"}, {"TK_ASSIGN_SUM", "r61"}, {"TK_COMMA", "r61"}, {"TK_DECREMENT", "r61"}, {"TK_DIV", "r61"}, {"TK_EQU", "r61"}, {"TK_GT", "r61"}, {"TK_GTE", "r61"}, {"TK_INCREMENT", "r61"}, {"TK_LB", "r61"}, {"TK_LPAREN", "r61"}, {"TK_LT", "r61"}, {"TK_LTE", "r61"}, {"TK_MOD", "r61"}, {"TK_MUL", "r61"}, {"TK_NEQ", "r61"}, {"TK_PERIOD", "r61"}, {"TK_RB", "r61"}, {"TK_RPAREN", "r61"}, {"TK_SEMI", "r61"}, {"TK_SUB", "r61"}};
	 actTab[6] = {{"TK_ADD", "r60"}, {"TK_ASSIGN", "r60"}, {"TK_ASSIGN_DIFF", "r60"}, {"TK_ASSIGN_SUM", "r60"}, {"TK_COMMA", "r60"}, {"TK_DECREMENT", "r60"}, {"TK_DIV", "r60"}, {"TK_EQU", "r60"}, {"TK_GT", "r60"}, {"TK_GTE", "r60"}, {"TK_INCREMENT", "r60"}, {"TK_LB", "r60"}, {"TK_LPAREN", "r60"}, {"TK_LT", "r60"}, {"TK_LTE", "r60"}, {"TK_MOD", "r60"}, {"TK_MUL", "r60"}, {"TK_NEQ", "r60"}, {"TK_PERIOD", "r60"}, {"TK_RB", "r60"}, {"TK_RPAREN", "r60"}, {"TK_SEMI", "r60"}, {"TK_SUB", "r60"}};
	 actTab[7] = {{"TK_ADD", "r56"}, {"TK_ASSIGN", "r56"}, {"TK_ASSIGN_DIFF", "r56"}, {"TK_ASSIGN_SUM", "r56"}, {"TK_COMMA", "r56"}, {"TK_DECREMENT", "r56"}, {"TK_DIV", "r56"}, {"TK_EQU", "r56"}, {"TK_GT", "r56"}, {"TK_GTE", "r56"}, {"TK_INCREMENT", "r56"}, {"TK_LB", "r56"}, {"TK_LPAREN", "r56"}, {"TK_LT", "r56"}, {"TK_LTE", "r56"}, {"TK_MOD", "r56"}, {"TK_MUL", "r56"}, {"TK_NEQ", "r56"}, {"TK_PERIOD", "r56"}, {"TK_RB", "r56"}, {"TK_RPAREN", "r56"}, {"TK_SEMI", "r56"}, {"TK_SUB", "r56"}};
	 actTab[8] = {{"TK_ADD", "r10"}, {"TK_ASSIGN", "r10"}, {"TK_ASSIGN_DIFF", "r10"}, {"TK_ASSIGN_SUM", "r10"}, {"TK_CLASS", "r10"}, {"TK_COMMA", "r10"}, {"TK_DECREMENT", "r10"}, {"TK_DIV", "r10"}, {"TK_EOI", "r10"}, {"TK_EQU", "r10"}, {"TK_FN", "r10"}, {"TK_GT", "r10"}, {"TK_GTE", "r10"}, {"TK_ID", "r10"}, {"TK_IF", "r10"}, {"TK_INCREMENT", "r10"}, {"TK_LAMBDA", "r10"}, {"TK_LB", "r10"}, {"TK_LCURLY", "r10"}, {"TK_LET", "r10"}, {"TK_LPAREN", "r10"}, {"TK_LT", "r10"}, {"TK_LTE", "r10"}, {"TK_MOD", "r10"}, {"TK_MUL", "r10"}, {"TK_NEQ", "r10"}, {"TK_NEW", "r10"}, {"TK_NOT", "r10"}, {"TK_NUM", "r10"}, {"TK_PERIOD", "r10"}, {"TK_PRINT", "r10"}, {"TK_PRINTLN", "r10"}, {"TK_RB", "r10"}, {"TK_RCURLY", "r10"}, {"TK_RETURN", "r10"}, {"TK_RPAREN", "r10"}, {"TK_SEMI", "r10"}, {"TK_STRING", "r10"}, {"TK_SUB", "r10"}, {"TK_WHILE", "r10"}};
	 actTab[9] = {{"TK_ADD", "r11"}, {"TK_ASSIGN", "r11"}, {"TK_ASSIGN_DIFF", "r11"}, {"TK_ASSIGN_SUM", "r11"}, {"TK_CLASS", "r11"}, {"TK_COMMA", "r11"}, {"TK_DECREMENT", "r11"}, {"TK_DIV", "r11"}, {"TK_EOI", "r11"}, {"TK_EQU", "r11"}, {"TK_FN", "r11"}, {"TK_GT", "r11"}, {"TK_GTE", "r11"}, {"TK_ID", "r11"}, {"TK_IF", "r11"}, {"TK_INCREMENT", "r11"}, {"TK_LAMBDA", "r11"}, {"TK_LB", "r11"}, {"TK_LCURLY", "r11"}, {"TK_LET", "r11"}, {"TK_LPAREN", "r11"}, {"TK_LT", "r11"}, {"TK_LTE", "r11"}, {"TK_MOD", "r11"}, {"TK_MUL", "r11"}, {"TK_NEQ", "r11"}, {"TK_NEW", "r11"}, {"TK_NOT", "r11"}, {"TK_NUM", "r11"}, {"TK_PERIOD", "r11"}, {"TK_PRINT", "r11"}, {"TK_PRINTLN", "r11"}, {"TK_RB", "r11"}, {"TK_RCURLY", "r11"}, {"TK_RETURN", "r11"}, {"TK_RPAREN", "r11"}, {"TK_SEMI", "r11"}, {"TK_STRING", "r11"}, {"TK_SUB", "r11"}, {"TK_WHILE", "r11"}};
	 actTab[10] = {{"TK_ADD", "r9"}, {"TK_ASSIGN", "r9"}, {"TK_ASSIGN_DIFF", "r9"}, {"TK_ASSIGN_SUM", "r9"}, {"TK_CLASS", "r9"}, {"TK_COMMA", "r9"}, {"TK_DECREMENT", "r9"}, {"TK_DIV", "r9"}, {"TK_EOI", "r9"}, {"TK_EQU", "r9"}, {"TK_FN", "r9"}, {"TK_GT", "r9"}, {"TK_GTE", "r9"}, {"TK_ID", "r9"}, {"TK_IF", "r9"}, {"TK_INCREMENT", "r9"}, {"TK_LAMBDA", "r9"}, {"TK_LB", "r9"}, {"TK_LCURLY", "r9"}, {"TK_LET", "r9"}, {"TK_LPAREN", "r9"}, {"TK_LT", "r9"}, {"TK_LTE", "r9"}, {"TK_MOD", "r9"}, {"TK_MUL", "r9"}, {"TK_NEQ", "r9"}, {"TK_NEW", "r9"}, {"TK_NOT", "r9"}, {"TK_NUM", "r9"}, {"TK_PERIOD", "r9"}, {"TK_PRINT", "r9"}, {"TK_PRINTLN", "r9"}, {"TK_RB", "r9"}, {"TK_RCURLY", "r9"}, {"TK_RETURN", "r9"}, {"TK_RPAREN", "r9"}, {"TK_SEMI", "r9"}, {"TK_STRING", "r9"}, {"TK_SUB", "r9"}, {"TK_WHILE", "r9"}};
	 actTab[11] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}};
	 actTab[12] = {{"TK_ADD", "r8"}, {"TK_ASSIGN", "r8"}, {"TK_ASSIGN_DIFF", "r8"}, {"TK_ASSIGN_SUM", "r8"}, {"TK_CLASS", "r8"}, {"TK_COMMA", "r8"}, {"TK_DECREMENT", "r8"}, {"TK_DIV", "r8"}, {"TK_EOI", "r8"}, {"TK_EQU", "r8"}, {"TK_FN", "r8"}, {"TK_GT", "r8"}, {"TK_GTE", "r8"}, {"TK_ID", "r8"}, {"TK_IF", "r8"}, {"TK_INCREMENT", "r8"}, {"TK_LAMBDA", "r8"}, {"TK_LB", "r8"}, {"TK_LCURLY", "r8"}, {"TK_LET", "r8"}, {"TK_LPAREN", "r8"}, {"TK_LT", "r8"}, {"TK_LTE", "r8"}, {"TK_MOD", "r8"}, {"TK_MUL", "r8"}, {"TK_NEQ", "r8"}, {"TK_NEW", "r8"}, {"TK_NOT", "r8"}, {"TK_NUM", "r8"}, {"TK_PERIOD", "r8"}, {"TK_PRINT", "r8"}, {"TK_PRINTLN", "r8"}, {"TK_RB", "r8"}, {"TK_RCURLY", "r8"}, {"TK_RETURN", "r8"}, {"TK_RPAREN", "r8"}, {"TK_SEMI", "r8"}, {"TK_STRING", "r8"}, {"TK_SUB", "r8"}, {"TK_WHILE", "r8"}};
	 actTab[13] = {{"TK_CLASS", "s36"}, {"TK_EOI", "r4"}, {"TK_FN", "s30"}, {"TK_ID", "s38"}, {"TK_IF", "s25"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LCURLY", "s28"}, {"TK_LET", "s16"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_PRINT", "s40"}, {"TK_PRINTLN", "s14"}, {"TK_RCURLY", "r4"}, {"TK_RETURN", "s31"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}, {"TK_WHILE", "s39"}};
	 actTab[14] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[15] = {{"TK_ADD", "r50"}, {"TK_ASSIGN", "r50"}, {"TK_ASSIGN_DIFF", "r50"}, {"TK_ASSIGN_SUM", "r50"}, {"TK_COMMA", "r50"}, {"TK_DECREMENT", "s54"}, {"TK_DIV", "r50"}, {"TK_EQU", "r50"}, {"TK_GT", "r50"}, {"TK_GTE", "r50"}, {"TK_INCREMENT", "s53"}, {"TK_LB", "s57"}, {"TK_LPAREN", "s55"}, {"TK_LT", "r50"}, {"TK_LTE", "r50"}, {"TK_MOD", "r50"}, {"TK_MUL", "r50"}, {"TK_NEQ", "r50"}, {"TK_PERIOD", "s56"}, {"TK_RB", "r50"}, {"TK_RPAREN", "r50"}, {"TK_SEMI", "r50"}, {"TK_SUB", "r50"}};
	 actTab[16] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[17] = {{"TK_ADD", "r13"}, {"TK_ASSIGN", "r13"}, {"TK_ASSIGN_DIFF", "r13"}, {"TK_ASSIGN_SUM", "r13"}, {"TK_CLASS", "r13"}, {"TK_COMMA", "r13"}, {"TK_DECREMENT", "r13"}, {"TK_DIV", "r13"}, {"TK_EOI", "r13"}, {"TK_EQU", "r13"}, {"TK_FN", "r13"}, {"TK_GT", "r13"}, {"TK_GTE", "r13"}, {"TK_ID", "r13"}, {"TK_IF", "r13"}, {"TK_INCREMENT", "r13"}, {"TK_LAMBDA", "r13"}, {"TK_LB", "r13"}, {"TK_LCURLY", "r13"}, {"TK_LET", "r13"}, {"TK_LPAREN", "r13"}, {"TK_LT", "r13"}, {"TK_LTE", "r13"}, {"TK_MOD", "r13"}, {"TK_MUL", "r13"}, {"TK_NEQ", "r13"}, {"TK_NEW", "r13"}, {"TK_NOT", "r13"}, {"TK_NUM", "r13"}, {"TK_PERIOD", "r13"}, {"TK_PRINT", "r13"}, {"TK_PRINTLN", "r13"}, {"TK_RB", "r13"}, {"TK_RCURLY", "r13"}, {"TK_RETURN", "r13"}, {"TK_RPAREN", "r13"}, {"TK_SEMI", "r13"}, {"TK_STRING", "r13"}, {"TK_SUB", "r13"}, {"TK_WHILE", "r13"}};
	 actTab[18] = {{"TK_ADD", "r6"}, {"TK_ASSIGN", "r6"}, {"TK_ASSIGN_DIFF", "r6"}, {"TK_ASSIGN_SUM", "r6"}, {"TK_CLASS", "r6"}, {"TK_COMMA", "r6"}, {"TK_DECREMENT", "r6"}, {"TK_DIV", "r6"}, {"TK_EOI", "r6"}, {"TK_EQU", "r6"}, {"TK_FN", "r6"}, {"TK_GT", "r6"}, {"TK_GTE", "r6"}, {"TK_ID", "r6"}, {"TK_IF", "r6"}, {"TK_INCREMENT", "r6"}, {"TK_LAMBDA", "r6"}, {"TK_LB", "r6"}, {"TK_LCURLY", "r6"}, {"TK_LET", "r6"}, {"TK_LPAREN", "r6"}, {"TK_LT", "r6"}, {"TK_LTE", "r6"}, {"TK_MOD", "r6"}, {"TK_MUL", "r6"}, {"TK_NEQ", "r6"}, {"TK_NEW", "r6"}, {"TK_NOT", "r6"}, {"TK_NUM", "r6"}, {"TK_PERIOD", "r6"}, {"TK_PRINT", "r6"}, {"TK_PRINTLN", "r6"}, {"TK_RB", "r6"}, {"TK_RCURLY", "r6"}, {"TK_RETURN", "r6"}, {"TK_RPAREN", "r6"}, {"TK_SEMI", "r6"}, {"TK_STRING", "r6"}, {"TK_SUB", "r6"}, {"TK_WHILE", "r6"}};
	 actTab[19] = {{"TK_ADD", "r5"}, {"TK_ASSIGN", "r5"}, {"TK_ASSIGN_DIFF", "r5"}, {"TK_ASSIGN_SUM", "r5"}, {"TK_CLASS", "r5"}, {"TK_COMMA", "r5"}, {"TK_DECREMENT", "r5"}, {"TK_DIV", "r5"}, {"TK_EOI", "r5"}, {"TK_EQU", "r5"}, {"TK_FN", "r5"}, {"TK_GT", "r5"}, {"TK_GTE", "r5"}, {"TK_ID", "r5"}, {"TK_IF", "r5"}, {"TK_INCREMENT", "r5"}, {"TK_LAMBDA", "r5"}, {"TK_LB", "r5"}, {"TK_LCURLY", "r5"}, {"TK_LET", "r5"}, {"TK_LPAREN", "r5"}, {"TK_LT", "r5"}, {"TK_LTE", "r5"}, {"TK_MOD", "r5"}, {"TK_MUL", "r5"}, {"TK_NEQ", "r5"}, {"TK_NEW", "r5"}, {"TK_NOT", "r5"}, {"TK_NUM", "r5"}, {"TK_PERIOD", "r5"}, {"TK_PRINT", "r5"}, {"TK_PRINTLN", "r5"}, {"TK_RB", "r5"}, {"TK_RCURLY", "r5"}, {"TK_RETURN", "r5"}, {"TK_RPAREN", "r5"}, {"TK_SEMI", "r5"}, {"TK_STRING", "r5"}, {"TK_SUB", "r5"}, {"TK_WHILE", "r5"}};
	 actTab[20] = {{"TK_ADD", "r12"}, {"TK_ASSIGN", "r12"}, {"TK_ASSIGN_DIFF", "r12"}, {"TK_ASSIGN_SUM", "r12"}, {"TK_CLASS", "r12"}, {"TK_COMMA", "r12"}, {"TK_DECREMENT", "r12"}, {"TK_DIV", "r12"}, {"TK_EOI", "r12"}, {"TK_EQU", "r12"}, {"TK_FN", "r12"}, {"TK_GT", "r12"}, {"TK_GTE", "r12"}, {"TK_ID", "r12"}, {"TK_IF", "r12"}, {"TK_INCREMENT", "r12"}, {"TK_LAMBDA", "r12"}, {"TK_LB", "r12"}, {"TK_LCURLY", "r12"}, {"TK_LET", "r12"}, {"TK_LPAREN", "r12"}, {"TK_LT", "r12"}, {"TK_LTE", "r12"}, {"TK_MOD", "r12"}, {"TK_MUL", "r12"}, {"TK_NEQ", "r12"}, {"TK_NEW", "r12"}, {"TK_NOT", "r12"}, {"TK_NUM", "r12"}, {"TK_PERIOD", "r12"}, {"TK_PRINT", "r12"}, {"TK_PRINTLN", "r12"}, {"TK_RB", "r12"}, {"TK_RCURLY", "r12"}, {"TK_RETURN", "r12"}, {"TK_RPAREN", "r12"}, {"TK_SEMI", "r12"}, {"TK_STRING", "r12"}, {"TK_SUB", "r12"}, {"TK_WHILE", "r12"}};
	 actTab[21] = {{"TK_SEMI", "s59"}};
	 actTab[22] = {{"TK_EOI", "r2"}};
	 actTab[23] = {{"TK_ADD", "r58"}, {"TK_ASSIGN", "r58"}, {"TK_ASSIGN_DIFF", "r58"}, {"TK_ASSIGN_SUM", "r58"}, {"TK_COMMA", "r58"}, {"TK_DECREMENT", "r58"}, {"TK_DIV", "r58"}, {"TK_EQU", "r58"}, {"TK_GT", "r58"}, {"TK_GTE", "r58"}, {"TK_INCREMENT", "r58"}, {"TK_LB", "r58"}, {"TK_LPAREN", "r58"}, {"TK_LT", "r58"}, {"TK_LTE", "r58"}, {"TK_MOD", "r58"}, {"TK_MUL", "r58"}, {"TK_NEQ", "r58"}, {"TK_PERIOD", "r58"}, {"TK_RB", "r58"}, {"TK_RPAREN", "r58"}, {"TK_SEMI", "r58"}, {"TK_SUB", "r58"}};
	 actTab[24] = {{"TK_ADD", "r47"}, {"TK_ASSIGN", "r47"}, {"TK_ASSIGN_DIFF", "r47"}, {"TK_ASSIGN_SUM", "r47"}, {"TK_COMMA", "r47"}, {"TK_DIV", "r47"}, {"TK_EQU", "r47"}, {"TK_GT", "r47"}, {"TK_GTE", "r47"}, {"TK_LT", "r47"}, {"TK_LTE", "r47"}, {"TK_MOD", "r47"}, {"TK_MUL", "r47"}, {"TK_NEQ", "r47"}, {"TK_RB", "r47"}, {"TK_RPAREN", "r47"}, {"TK_SEMI", "r47"}, {"TK_SUB", "r47"}};
	 actTab[25] = {{"TK_LPAREN", "s60"}};
	 actTab[26] = {{"TK_ADD", "r7"}, {"TK_ASSIGN", "r7"}, {"TK_ASSIGN_DIFF", "r7"}, {"TK_ASSIGN_SUM", "r7"}, {"TK_CLASS", "r7"}, {"TK_COMMA", "r7"}, {"TK_DECREMENT", "r7"}, {"TK_DIV", "r7"}, {"TK_EOI", "r7"}, {"TK_EQU", "r7"}, {"TK_FN", "r7"}, {"TK_GT", "r7"}, {"TK_GTE", "r7"}, {"TK_ID", "r7"}, {"TK_IF", "r7"}, {"TK_INCREMENT", "r7"}, {"TK_LAMBDA", "r7"}, {"TK_LB", "r7"}, {"TK_LCURLY", "r7"}, {"TK_LET", "r7"}, {"TK_LPAREN", "r7"}, {"TK_LT", "r7"}, {"TK_LTE", "r7"}, {"TK_MOD", "r7"}, {"TK_MUL", "r7"}, {"TK_NEQ", "r7"}, {"TK_NEW", "r7"}, {"TK_NOT", "r7"}, {"TK_NUM", "r7"}, {"TK_PERIOD", "r7"}, {"TK_PRINT", "r7"}, {"TK_PRINTLN", "r7"}, {"TK_RB", "r7"}, {"TK_RCURLY", "r7"}, {"TK_RETURN", "r7"}, {"TK_RPAREN", "r7"}, {"TK_SEMI", "r7"}, {"TK_STRING", "r7"}, {"TK_SUB", "r7"}, {"TK_WHILE", "r7"}};
	 actTab[27] = {{"TK_ADD", "s62"}, {"TK_ASSIGN", "r40"}, {"TK_ASSIGN_DIFF", "r40"}, {"TK_ASSIGN_SUM", "r40"}, {"TK_COMMA", "r40"}, {"TK_EQU", "r40"}, {"TK_GT", "r40"}, {"TK_GTE", "r40"}, {"TK_LT", "r40"}, {"TK_LTE", "r40"}, {"TK_NEQ", "r40"}, {"TK_RB", "r40"}, {"TK_RPAREN", "r40"}, {"TK_SEMI", "r40"}, {"TK_SUB", "s61"}};
	 actTab[28] = {{"TK_CLASS", "s36"}, {"TK_FN", "s30"}, {"TK_ID", "s38"}, {"TK_IF", "s25"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LCURLY", "s28"}, {"TK_LET", "s16"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_PRINT", "s40"}, {"TK_PRINTLN", "s14"}, {"TK_RETURN", "s31"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}, {"TK_WHILE", "s39"}};
	 actTab[29] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[30] = {{"TK_ID", "s65"}};
	 actTab[31] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[32] = {{"TK_ADD", "r63"}, {"TK_ASSIGN", "r63"}, {"TK_ASSIGN_DIFF", "r63"}, {"TK_ASSIGN_SUM", "r63"}, {"TK_COMMA", "r63"}, {"TK_DECREMENT", "r63"}, {"TK_DIV", "r63"}, {"TK_EQU", "r63"}, {"TK_GT", "r63"}, {"TK_GTE", "r63"}, {"TK_INCREMENT", "r63"}, {"TK_LB", "r63"}, {"TK_LPAREN", "r63"}, {"TK_LT", "r63"}, {"TK_LTE", "r63"}, {"TK_MOD", "r63"}, {"TK_MUL", "r63"}, {"TK_NEQ", "r63"}, {"TK_PERIOD", "r63"}, {"TK_RB", "r63"}, {"TK_RPAREN", "r63"}, {"TK_SEMI", "r63"}, {"TK_SUB", "r63"}};
	 actTab[33] = {{"TK_ADD", "r43"}, {"TK_ASSIGN", "r43"}, {"TK_ASSIGN_DIFF", "r43"}, {"TK_ASSIGN_SUM", "r43"}, {"TK_COMMA", "r43"}, {"TK_DIV", "s68"}, {"TK_EQU", "r43"}, {"TK_GT", "r43"}, {"TK_GTE", "r43"}, {"TK_LT", "r43"}, {"TK_LTE", "r43"}, {"TK_MOD", "s67"}, {"TK_MUL", "s69"}, {"TK_NEQ", "r43"}, {"TK_RB", "r43"}, {"TK_RPAREN", "r43"}, {"TK_SEMI", "r43"}, {"TK_SUB", "r43"}};
	 actTab[34] = {{"TK_ASSIGN", "s74"}, {"TK_ASSIGN_DIFF", "s71"}, {"TK_ASSIGN_SUM", "s73"}, {"TK_EQU", "s70"}, {"TK_NEQ", "s72"}, {"TK_RPAREN", "r32"}, {"TK_SEMI", "r32"}};
	 actTab[35] = {{"$", "accept"}};
	 actTab[36] = {{"TK_ID", "s75"}};
	 actTab[37] = {{"TK_ASSIGN", "r35"}, {"TK_ASSIGN_DIFF", "r35"}, {"TK_ASSIGN_SUM", "r35"}, {"TK_COMMA", "r35"}, {"TK_EQU", "r35"}, {"TK_GT", "s78"}, {"TK_GTE", "s77"}, {"TK_LT", "s79"}, {"TK_LTE", "s76"}, {"TK_NEQ", "r35"}, {"TK_RB", "r35"}, {"TK_RPAREN", "r35"}, {"TK_SEMI", "r35"}};
	 actTab[38] = {{"TK_ADD", "r59"}, {"TK_ASSIGN", "r59"}, {"TK_ASSIGN_DIFF", "r59"}, {"TK_ASSIGN_SUM", "r59"}, {"TK_COMMA", "r59"}, {"TK_DECREMENT", "r59"}, {"TK_DIV", "r59"}, {"TK_EQU", "r59"}, {"TK_GT", "r59"}, {"TK_GTE", "r59"}, {"TK_INCREMENT", "r59"}, {"TK_LB", "r59"}, {"TK_LPAREN", "r59"}, {"TK_LT", "r59"}, {"TK_LTE", "r59"}, {"TK_MOD", "r59"}, {"TK_MUL", "r59"}, {"TK_NEQ", "r59"}, {"TK_PERIOD", "r59"}, {"TK_RB", "r59"}, {"TK_RPAREN", "r59"}, {"TK_SEMI", "r59"}, {"TK_SUB", "r59"}};
	 actTab[39] = {{"TK_LPAREN", "s80"}};
	 actTab[40] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[41] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}};
	 actTab[42] = {{"TK_COMMA", "s83"}, {"TK_RPAREN", "r18"}};
	 actTab[43] = {{"TK_RPAREN", "r14"}};
	 actTab[44] = {{"TK_ID", "s84"}};
	 actTab[45] = {{"TK_RPAREN", "s85"}};
	 actTab[46] = {{"TK_LPAREN", "s86"}};
	 actTab[47] = {{"TK_RB", "s87"}};
	 actTab[48] = {{"TK_RB", "r64"}, {"TK_RPAREN", "r64"}};
	 actTab[49] = {{"TK_COMMA", "s88"}, {"TK_EQU", "s70"}, {"TK_NEQ", "s72"}, {"TK_RB", "r67"}, {"TK_RPAREN", "r67"}};
	 actTab[50] = {{"TK_ADD", "r48"}, {"TK_ASSIGN", "r48"}, {"TK_ASSIGN_DIFF", "r48"}, {"TK_ASSIGN_SUM", "r48"}, {"TK_COMMA", "r48"}, {"TK_DECREMENT", "s54"}, {"TK_DIV", "r48"}, {"TK_EQU", "r48"}, {"TK_GT", "r48"}, {"TK_GTE", "r48"}, {"TK_INCREMENT", "s53"}, {"TK_LB", "s57"}, {"TK_LPAREN", "s55"}, {"TK_LT", "r48"}, {"TK_LTE", "r48"}, {"TK_MOD", "r48"}, {"TK_MUL", "r48"}, {"TK_NEQ", "r48"}, {"TK_PERIOD", "s56"}, {"TK_RB", "r48"}, {"TK_RPAREN", "r48"}, {"TK_SEMI", "r48"}, {"TK_SUB", "r48"}};
	 actTab[51] = {{"TK_EOI", "r3"}, {"TK_RCURLY", "r3"}};
	 actTab[52] = {{"TK_SEMI", "s89"}};
	 actTab[53] = {{"TK_ADD", "r55"}, {"TK_ASSIGN", "r55"}, {"TK_ASSIGN_DIFF", "r55"}, {"TK_ASSIGN_SUM", "r55"}, {"TK_COMMA", "r55"}, {"TK_DECREMENT", "r55"}, {"TK_DIV", "r55"}, {"TK_EQU", "r55"}, {"TK_GT", "r55"}, {"TK_GTE", "r55"}, {"TK_INCREMENT", "r55"}, {"TK_LB", "r55"}, {"TK_LPAREN", "r55"}, {"TK_LT", "r55"}, {"TK_LTE", "r55"}, {"TK_MOD", "r55"}, {"TK_MUL", "r55"}, {"TK_NEQ", "r55"}, {"TK_PERIOD", "r55"}, {"TK_RB", "r55"}, {"TK_RPAREN", "r55"}, {"TK_SEMI", "r55"}, {"TK_SUB", "r55"}};
	 actTab[54] = {{"TK_ADD", "r54"}, {"TK_ASSIGN", "r54"}, {"TK_ASSIGN_DIFF", "r54"}, {"TK_ASSIGN_SUM", "r54"}, {"TK_COMMA", "r54"}, {"TK_DECREMENT", "r54"}, {"TK_DIV", "r54"}, {"TK_EQU", "r54"}, {"TK_GT", "r54"}, {"TK_GTE", "r54"}, {"TK_INCREMENT", "r54"}, {"TK_LB", "r54"}, {"TK_LPAREN", "r54"}, {"TK_LT", "r54"}, {"TK_LTE", "r54"}, {"TK_MOD", "r54"}, {"TK_MUL", "r54"}, {"TK_NEQ", "r54"}, {"TK_PERIOD", "r54"}, {"TK_RB", "r54"}, {"TK_RPAREN", "r54"}, {"TK_SEMI", "r54"}, {"TK_SUB", "r54"}};
	 actTab[55] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_RPAREN", "r65"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[56] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}};
	 actTab[57] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}};
	 actTab[58] = {{"TK_SEMI", "s93"}};
	 actTab[59] = {{"TK_ADD", "r28"}, {"TK_ASSIGN", "r28"}, {"TK_ASSIGN_DIFF", "r28"}, {"TK_ASSIGN_SUM", "r28"}, {"TK_CLASS", "r28"}, {"TK_COMMA", "r28"}, {"TK_DECREMENT", "r28"}, {"TK_DIV", "r28"}, {"TK_EOI", "r28"}, {"TK_EQU", "r28"}, {"TK_FN", "r28"}, {"TK_GT", "r28"}, {"TK_GTE", "r28"}, {"TK_ID", "r28"}, {"TK_IF", "r28"}, {"TK_INCREMENT", "r28"}, {"TK_LAMBDA", "r28"}, {"TK_LB", "r28"}, {"TK_LCURLY", "r28"}, {"TK_LET", "r28"}, {"TK_LPAREN", "r28"}, {"TK_LT", "r28"}, {"TK_LTE", "r28"}, {"TK_MOD", "r28"}, {"TK_MUL", "r28"}, {"TK_NEQ", "r28"}, {"TK_NEW", "r28"}, {"TK_NOT", "r28"}, {"TK_NUM", "r28"}, {"TK_PERIOD", "r28"}, {"TK_PRINT", "r28"}, {"TK_PRINTLN", "r28"}, {"TK_RB", "r28"}, {"TK_RCURLY", "r28"}, {"TK_RETURN", "r28"}, {"TK_RPAREN", "r28"}, {"TK_SEMI", "r28"}, {"TK_STRING", "r28"}, {"TK_SUB", "r28"}, {"TK_WHILE", "r28"}};
	 actTab[60] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[61] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[62] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[63] = {{"TK_RCURLY", "s97"}};
	 actTab[64] = {{"TK_RPAREN", "s98"}};
	 actTab[65] = {{"TK_LPAREN", "s99"}};
	 actTab[66] = {{"TK_SEMI", "s100"}};
	 actTab[67] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[68] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[69] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[70] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[71] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[72] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[73] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[74] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[75] = {{"TK_LCURLY", "s28"}};
	 actTab[76] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[77] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[78] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[79] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[80] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[81] = {{"TK_SEMI", "s115"}};
	 actTab[82] = {{"TK_ADD", "r49"}, {"TK_ASSIGN", "r49"}, {"TK_ASSIGN_DIFF", "r49"}, {"TK_ASSIGN_SUM", "r49"}, {"TK_COMMA", "r49"}, {"TK_DECREMENT", "s54"}, {"TK_DIV", "r49"}, {"TK_EQU", "r49"}, {"TK_GT", "r49"}, {"TK_GTE", "r49"}, {"TK_INCREMENT", "s53"}, {"TK_LB", "s57"}, {"TK_LPAREN", "s55"}, {"TK_LT", "r49"}, {"TK_LTE", "r49"}, {"TK_MOD", "r49"}, {"TK_MUL", "r49"}, {"TK_NEQ", "r49"}, {"TK_PERIOD", "s56"}, {"TK_RB", "r49"}, {"TK_RPAREN", "r49"}, {"TK_SEMI", "r49"}, {"TK_SUB", "r49"}};
	 actTab[83] = {{"TK_LET", "s44"}};
	 actTab[84] = {{"TK_COMMA", "r16"}, {"TK_RPAREN", "r16"}};
	 actTab[85] = {{"TK_PRODUCE", "s117"}};
	 actTab[86] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_RPAREN", "r65"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[87] = {{"TK_ADD", "r68"}, {"TK_ASSIGN", "r68"}, {"TK_ASSIGN_DIFF", "r68"}, {"TK_ASSIGN_SUM", "r68"}, {"TK_COMMA", "r68"}, {"TK_DECREMENT", "r68"}, {"TK_DIV", "r68"}, {"TK_EQU", "r68"}, {"TK_GT", "r68"}, {"TK_GTE", "r68"}, {"TK_INCREMENT", "r68"}, {"TK_LB", "r68"}, {"TK_LPAREN", "r68"}, {"TK_LT", "r68"}, {"TK_LTE", "r68"}, {"TK_MOD", "r68"}, {"TK_MUL", "r68"}, {"TK_NEQ", "r68"}, {"TK_PERIOD", "r68"}, {"TK_RB", "r68"}, {"TK_RPAREN", "r68"}, {"TK_SEMI", "r68"}, {"TK_SUB", "r68"}};
	 actTab[88] = {{"TK_ID", "s38"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}};
	 actTab[89] = {{"TK_ADD", "r21"}, {"TK_ASSIGN", "r21"}, {"TK_ASSIGN_DIFF", "r21"}, {"TK_ASSIGN_SUM", "r21"}, {"TK_CLASS", "r21"}, {"TK_COMMA", "r21"}, {"TK_DECREMENT", "r21"}, {"TK_DIV", "r21"}, {"TK_EOI", "r21"}, {"TK_EQU", "r21"}, {"TK_FN", "r21"}, {"TK_GT", "r21"}, {"TK_GTE", "r21"}, {"TK_ID", "r21"}, {"TK_IF", "r21"}, {"TK_INCREMENT", "r21"}, {"TK_LAMBDA", "r21"}, {"TK_LB", "r21"}, {"TK_LCURLY", "r21"}, {"TK_LET", "r21"}, {"TK_LPAREN", "r21"}, {"TK_LT", "r21"}, {"TK_LTE", "r21"}, {"TK_MOD", "r21"}, {"TK_MUL", "r21"}, {"TK_NEQ", "r21"}, {"TK_NEW", "r21"}, {"TK_NOT", "r21"}, {"TK_NUM", "r21"}, {"TK_PERIOD", "r21"}, {"TK_PRINT", "r21"}, {"TK_PRINTLN", "r21"}, {"TK_RB", "r21"}, {"TK_RCURLY", "r21"}, {"TK_RETURN", "r21"}, {"TK_RPAREN", "r21"}, {"TK_SEMI", "r21"}, {"TK_STRING", "r21"}, {"TK_SUB", "r21"}, {"TK_WHILE", "r21"}};
	 actTab[90] = {{"TK_RPAREN", "s120"}};
	 actTab[91] = {{"TK_ADD", "r53"}, {"TK_ASSIGN", "r53"}, {"TK_ASSIGN_DIFF", "r53"}, {"TK_ASSIGN_SUM", "r53"}, {"TK_COMMA", "r53"}, {"TK_DECREMENT", "r53"}, {"TK_DIV", "r53"}, {"TK_EQU", "r53"}, {"TK_GT", "r53"}, {"TK_GTE", "r53"}, {"TK_INCREMENT", "r53"}, {"TK_LB", "r53"}, {"TK_LPAREN", "r53"}, {"TK_LT", "r53"}, {"TK_LTE", "r53"}, {"TK_MOD", "r53"}, {"TK_MUL", "r53"}, {"TK_NEQ", "r53"}, {"TK_PERIOD", "r53"}, {"TK_RB", "r53"}, {"TK_RPAREN", "r53"}, {"TK_SEMI", "r53"}, {"TK_SUB", "r53"}};
	 actTab[92] = {{"TK_RB", "s121"}};
	 actTab[93] = {{"TK_ADD", "r19"}, {"TK_ASSIGN", "r19"}, {"TK_ASSIGN_DIFF", "r19"}, {"TK_ASSIGN_SUM", "r19"}, {"TK_CLASS", "r19"}, {"TK_COMMA", "r19"}, {"TK_DECREMENT", "r19"}, {"TK_DIV", "r19"}, {"TK_EOI", "r19"}, {"TK_EQU", "r19"}, {"TK_FN", "r19"}, {"TK_GT", "r19"}, {"TK_GTE", "r19"}, {"TK_ID", "r19"}, {"TK_IF", "r19"}, {"TK_INCREMENT", "r19"}, {"TK_LAMBDA", "r19"}, {"TK_LB", "r19"}, {"TK_LCURLY", "r19"}, {"TK_LET", "r19"}, {"TK_LPAREN", "r19"}, {"TK_LT", "r19"}, {"TK_LTE", "r19"}, {"TK_MOD", "r19"}, {"TK_MUL", "r19"}, {"TK_NEQ", "r19"}, {"TK_NEW", "r19"}, {"TK_NOT", "r19"}, {"TK_NUM", "r19"}, {"TK_PERIOD", "r19"}, {"TK_PRINT", "r19"}, {"TK_PRINTLN", "r19"}, {"TK_RB", "r19"}, {"TK_RCURLY", "r19"}, {"TK_RETURN", "r19"}, {"TK_RPAREN", "r19"}, {"TK_SEMI", "r19"}, {"TK_STRING", "r19"}, {"TK_SUB", "r19"}, {"TK_WHILE", "r19"}};
	 actTab[94] = {{"TK_RPAREN", "s122"}};
	 actTab[95] = {{"TK_ADD", "r42"}, {"TK_ASSIGN", "r42"}, {"TK_ASSIGN_DIFF", "r42"}, {"TK_ASSIGN_SUM", "r42"}, {"TK_COMMA", "r42"}, {"TK_DIV", "s68"}, {"TK_EQU", "r42"}, {"TK_GT", "r42"}, {"TK_GTE", "r42"}, {"TK_LT", "r42"}, {"TK_LTE", "r42"}, {"TK_MOD", "s67"}, {"TK_MUL", "s69"}, {"TK_NEQ", "r42"}, {"TK_RB", "r42"}, {"TK_RPAREN", "r42"}, {"TK_SEMI", "r42"}, {"TK_SUB", "r42"}};
	 actTab[96] = {{"TK_ADD", "r41"}, {"TK_ASSIGN", "r41"}, {"TK_ASSIGN_DIFF", "r41"}, {"TK_ASSIGN_SUM", "r41"}, {"TK_COMMA", "r41"}, {"TK_DIV", "s68"}, {"TK_EQU", "r41"}, {"TK_GT", "r41"}, {"TK_GTE", "r41"}, {"TK_LT", "r41"}, {"TK_LTE", "r41"}, {"TK_MOD", "s67"}, {"TK_MUL", "s69"}, {"TK_NEQ", "r41"}, {"TK_RB", "r41"}, {"TK_RPAREN", "r41"}, {"TK_SEMI", "r41"}, {"TK_SUB", "r41"}};
	 actTab[97] = {{"TK_ADD", "r22"}, {"TK_ASSIGN", "r22"}, {"TK_ASSIGN_DIFF", "r22"}, {"TK_ASSIGN_SUM", "r22"}, {"TK_CLASS", "r22"}, {"TK_COMMA", "r22"}, {"TK_DECREMENT", "r22"}, {"TK_DIV", "r22"}, {"TK_EOI", "r22"}, {"TK_EQU", "r22"}, {"TK_FN", "r22"}, {"TK_GT", "r22"}, {"TK_GTE", "r22"}, {"TK_ID", "r22"}, {"TK_IF", "r22"}, {"TK_INCREMENT", "r22"}, {"TK_LAMBDA", "r22"}, {"TK_LB", "r22"}, {"TK_LCURLY", "r22"}, {"TK_LET", "r22"}, {"TK_LPAREN", "r22"}, {"TK_LT", "r22"}, {"TK_LTE", "r22"}, {"TK_MOD", "r22"}, {"TK_MUL", "r22"}, {"TK_NEQ", "r22"}, {"TK_NEW", "r22"}, {"TK_NOT", "r22"}, {"TK_NUM", "r22"}, {"TK_PERIOD", "r22"}, {"TK_PRINT", "r22"}, {"TK_PRINTLN", "r22"}, {"TK_RB", "r22"}, {"TK_RCURLY", "r22"}, {"TK_RETURN", "r22"}, {"TK_RPAREN", "r22"}, {"TK_SEMI", "r22"}, {"TK_STRING", "r22"}, {"TK_SUB", "r22"}, {"TK_WHILE", "r22"}};
	 actTab[98] = {{"TK_ADD", "r57"}, {"TK_ASSIGN", "r57"}, {"TK_ASSIGN_DIFF", "r57"}, {"TK_ASSIGN_SUM", "r57"}, {"TK_COMMA", "r57"}, {"TK_DECREMENT", "r57"}, {"TK_DIV", "r57"}, {"TK_EQU", "r57"}, {"TK_GT", "r57"}, {"TK_GTE", "r57"}, {"TK_INCREMENT", "r57"}, {"TK_LB", "r57"}, {"TK_LPAREN", "r57"}, {"TK_LT", "r57"}, {"TK_LTE", "r57"}, {"TK_MOD", "r57"}, {"TK_MUL", "r57"}, {"TK_NEQ", "r57"}, {"TK_PERIOD", "r57"}, {"TK_RB", "r57"}, {"TK_RPAREN", "r57"}, {"TK_SEMI", "r57"}, {"TK_SUB", "r57"}};
	 actTab[99] = {{"TK_LET", "s44"}, {"TK_RPAREN", "r15"}};
	 actTab[100] = {{"TK_ADD", "r27"}, {"TK_ASSIGN", "r27"}, {"TK_ASSIGN_DIFF", "r27"}, {"TK_ASSIGN_SUM", "r27"}, {"TK_CLASS", "r27"}, {"TK_COMMA", "r27"}, {"TK_DECREMENT", "r27"}, {"TK_DIV", "r27"}, {"TK_EOI", "r27"}, {"TK_EQU", "r27"}, {"TK_FN", "r27"}, {"TK_GT", "r27"}, {"TK_GTE", "r27"}, {"TK_ID", "r27"}, {"TK_IF", "r27"}, {"TK_INCREMENT", "r27"}, {"TK_LAMBDA", "r27"}, {"TK_LB", "r27"}, {"TK_LCURLY", "r27"}, {"TK_LET", "r27"}, {"TK_LPAREN", "r27"}, {"TK_LT", "r27"}, {"TK_LTE", "r27"}, {"TK_MOD", "r27"}, {"TK_MUL", "r27"}, {"TK_NEQ", "r27"}, {"TK_NEW", "r27"}, {"TK_NOT", "r27"}, {"TK_NUM", "r27"}, {"TK_PERIOD", "r27"}, {"TK_PRINT", "r27"}, {"TK_PRINTLN", "r27"}, {"TK_RB", "r27"}, {"TK_RCURLY", "r27"}, {"TK_RETURN", "r27"}, {"TK_RPAREN", "r27"}, {"TK_SEMI", "r27"}, {"TK_STRING", "r27"}, {"TK_SUB", "r27"}, {"TK_WHILE", "r27"}};
	 actTab[101] = {{"TK_ADD", "r46"}, {"TK_ASSIGN", "r46"}, {"TK_ASSIGN_DIFF", "r46"}, {"TK_ASSIGN_SUM", "r46"}, {"TK_COMMA", "r46"}, {"TK_DIV", "r46"}, {"TK_EQU", "r46"}, {"TK_GT", "r46"}, {"TK_GTE", "r46"}, {"TK_LT", "r46"}, {"TK_LTE", "r46"}, {"TK_MOD", "r46"}, {"TK_MUL", "r46"}, {"TK_NEQ", "r46"}, {"TK_RB", "r46"}, {"TK_RPAREN", "r46"}, {"TK_SEMI", "r46"}, {"TK_SUB", "r46"}};
	 actTab[102] = {{"TK_ADD", "r45"}, {"TK_ASSIGN", "r45"}, {"TK_ASSIGN_DIFF", "r45"}, {"TK_ASSIGN_SUM", "r45"}, {"TK_COMMA", "r45"}, {"TK_DIV", "r45"}, {"TK_EQU", "r45"}, {"TK_GT", "r45"}, {"TK_GTE", "r45"}, {"TK_LT", "r45"}, {"TK_LTE", "r45"}, {"TK_MOD", "r45"}, {"TK_MUL", "r45"}, {"TK_NEQ", "r45"}, {"TK_RB", "r45"}, {"TK_RPAREN", "r45"}, {"TK_SEMI", "r45"}, {"TK_SUB", "r45"}};
	 actTab[103] = {{"TK_ADD", "r44"}, {"TK_ASSIGN", "r44"}, {"TK_ASSIGN_DIFF", "r44"}, {"TK_ASSIGN_SUM", "r44"}, {"TK_COMMA", "r44"}, {"TK_DIV", "r44"}, {"TK_EQU", "r44"}, {"TK_GT", "r44"}, {"TK_GTE", "r44"}, {"TK_LT", "r44"}, {"TK_LTE", "r44"}, {"TK_MOD", "r44"}, {"TK_MUL", "r44"}, {"TK_NEQ", "r44"}, {"TK_RB", "r44"}, {"TK_RPAREN", "r44"}, {"TK_SEMI", "r44"}, {"TK_SUB", "r44"}};
	 actTab[104] = {{"TK_ASSIGN", "r33"}, {"TK_ASSIGN_DIFF", "r33"}, {"TK_ASSIGN_SUM", "r33"}, {"TK_COMMA", "r33"}, {"TK_EQU", "r33"}, {"TK_GT", "s78"}, {"TK_GTE", "s77"}, {"TK_LT", "s79"}, {"TK_LTE", "s76"}, {"TK_NEQ", "r33"}, {"TK_RB", "r33"}, {"TK_RPAREN", "r33"}, {"TK_SEMI", "r33"}};
	 actTab[105] = {{"TK_RPAREN", "r31"}, {"TK_SEMI", "r31"}};
	 actTab[106] = {{"TK_ASSIGN", "r34"}, {"TK_ASSIGN_DIFF", "r34"}, {"TK_ASSIGN_SUM", "r34"}, {"TK_COMMA", "r34"}, {"TK_EQU", "r34"}, {"TK_GT", "s78"}, {"TK_GTE", "s77"}, {"TK_LT", "s79"}, {"TK_LTE", "s76"}, {"TK_NEQ", "r34"}, {"TK_RB", "r34"}, {"TK_RPAREN", "r34"}, {"TK_SEMI", "r34"}};
	 actTab[107] = {{"TK_RPAREN", "r30"}, {"TK_SEMI", "r30"}};
	 actTab[108] = {{"TK_RPAREN", "r29"}, {"TK_SEMI", "r29"}};
	 actTab[109] = {{"TK_SEMI", "s124"}};
	 actTab[110] = {{"TK_ADD", "s62"}, {"TK_ASSIGN", "r39"}, {"TK_ASSIGN_DIFF", "r39"}, {"TK_ASSIGN_SUM", "r39"}, {"TK_COMMA", "r39"}, {"TK_EQU", "r39"}, {"TK_GT", "r39"}, {"TK_GTE", "r39"}, {"TK_LT", "r39"}, {"TK_LTE", "r39"}, {"TK_NEQ", "r39"}, {"TK_RB", "r39"}, {"TK_RPAREN", "r39"}, {"TK_SEMI", "r39"}, {"TK_SUB", "s61"}};
	 actTab[111] = {{"TK_ADD", "s62"}, {"TK_ASSIGN", "r38"}, {"TK_ASSIGN_DIFF", "r38"}, {"TK_ASSIGN_SUM", "r38"}, {"TK_COMMA", "r38"}, {"TK_EQU", "r38"}, {"TK_GT", "r38"}, {"TK_GTE", "r38"}, {"TK_LT", "r38"}, {"TK_LTE", "r38"}, {"TK_NEQ", "r38"}, {"TK_RB", "r38"}, {"TK_RPAREN", "r38"}, {"TK_SEMI", "r38"}, {"TK_SUB", "s61"}};
	 actTab[112] = {{"TK_ADD", "s62"}, {"TK_ASSIGN", "r37"}, {"TK_ASSIGN_DIFF", "r37"}, {"TK_ASSIGN_SUM", "r37"}, {"TK_COMMA", "r37"}, {"TK_EQU", "r37"}, {"TK_GT", "r37"}, {"TK_GTE", "r37"}, {"TK_LT", "r37"}, {"TK_LTE", "r37"}, {"TK_NEQ", "r37"}, {"TK_RB", "r37"}, {"TK_RPAREN", "r37"}, {"TK_SEMI", "r37"}, {"TK_SUB", "s61"}};
	 actTab[113] = {{"TK_ADD", "s62"}, {"TK_ASSIGN", "r36"}, {"TK_ASSIGN_DIFF", "r36"}, {"TK_ASSIGN_SUM", "r36"}, {"TK_COMMA", "r36"}, {"TK_EQU", "r36"}, {"TK_GT", "r36"}, {"TK_GTE", "r36"}, {"TK_LT", "r36"}, {"TK_LTE", "r36"}, {"TK_NEQ", "r36"}, {"TK_RB", "r36"}, {"TK_RPAREN", "r36"}, {"TK_SEMI", "r36"}, {"TK_SUB", "s61"}};
	 actTab[114] = {{"TK_RPAREN", "s125"}};
	 actTab[115] = {{"TK_ADD", "r20"}, {"TK_ASSIGN", "r20"}, {"TK_ASSIGN_DIFF", "r20"}, {"TK_ASSIGN_SUM", "r20"}, {"TK_CLASS", "r20"}, {"TK_COMMA", "r20"}, {"TK_DECREMENT", "r20"}, {"TK_DIV", "r20"}, {"TK_EOI", "r20"}, {"TK_EQU", "r20"}, {"TK_FN", "r20"}, {"TK_GT", "r20"}, {"TK_GTE", "r20"}, {"TK_ID", "r20"}, {"TK_IF", "r20"}, {"TK_INCREMENT", "r20"}, {"TK_LAMBDA", "r20"}, {"TK_LB", "r20"}, {"TK_LCURLY", "r20"}, {"TK_LET", "r20"}, {"TK_LPAREN", "r20"}, {"TK_LT", "r20"}, {"TK_LTE", "r20"}, {"TK_MOD", "r20"}, {"TK_MUL", "r20"}, {"TK_NEQ", "r20"}, {"TK_NEW", "r20"}, {"TK_NOT", "r20"}, {"TK_NUM", "r20"}, {"TK_PERIOD", "r20"}, {"TK_PRINT", "r20"}, {"TK_PRINTLN", "r20"}, {"TK_RB", "r20"}, {"TK_RCURLY", "r20"}, {"TK_RETURN", "r20"}, {"TK_RPAREN", "r20"}, {"TK_SEMI", "r20"}, {"TK_STRING", "r20"}, {"TK_SUB", "r20"}, {"TK_WHILE", "r20"}};
	 actTab[116] = {{"TK_RPAREN", "r17"}};
	 actTab[117] = {{"TK_CLASS", "s36"}, {"TK_FN", "s30"}, {"TK_ID", "s38"}, {"TK_IF", "s25"}, {"TK_LAMBDA", "s1"}, {"TK_LB", "s3"}, {"TK_LCURLY", "s28"}, {"TK_LET", "s16"}, {"TK_LPAREN", "s29"}, {"TK_NEW", "s2"}, {"TK_NOT", "s41"}, {"TK_NUM", "s23"}, {"TK_PRINT", "s40"}, {"TK_PRINTLN", "s14"}, {"TK_RETURN", "s31"}, {"TK_STRING", "s6"}, {"TK_SUB", "s11"}, {"TK_WHILE", "s39"}};
	 actTab[118] = {{"TK_RPAREN", "s127"}};
	 actTab[119] = {{"TK_RB", "r66"}, {"TK_RPAREN", "r66"}};
	 actTab[120] = {{"TK_ADD", "r52"}, {"TK_ASSIGN", "r52"}, {"TK_ASSIGN_DIFF", "r52"}, {"TK_ASSIGN_SUM", "r52"}, {"TK_COMMA", "r52"}, {"TK_DECREMENT", "r52"}, {"TK_DIV", "r52"}, {"TK_EQU", "r52"}, {"TK_GT", "r52"}, {"TK_GTE", "r52"}, {"TK_INCREMENT", "r52"}, {"TK_LB", "r52"}, {"TK_LPAREN", "r52"}, {"TK_LT", "r52"}, {"TK_LTE", "r52"}, {"TK_MOD", "r52"}, {"TK_MUL", "r52"}, {"TK_NEQ", "r52"}, {"TK_PERIOD", "r52"}, {"TK_RB", "r52"}, {"TK_RPAREN", "r52"}, {"TK_SEMI", "r52"}, {"TK_SUB", "r52"}};
	 actTab[121] = {{"TK_ADD", "r51"}, {"TK_ASSIGN", "r51"}, {"TK_ASSIGN_DIFF", "r51"}, {"TK_ASSIGN_SUM", "r51"}, {"TK_COMMA", "r51"}, {"TK_DECREMENT", "r51"}, {"TK_DIV", "r51"}, {"TK_EQU", "r51"}, {"TK_GT", "r51"}, {"TK_GTE", "r51"}, {"TK_INCREMENT", "r51"}, {"TK_LB", "r51"}, {"TK_LPAREN", "r51"}, {"TK_LT", "r51"}, {"TK_LTE", "r51"}, {"TK_MOD", "r51"}, {"TK_MUL", "r51"}, {"TK_NEQ", "r51"}, {"TK_PERIOD", "r51"}, {"TK_RB", "r51"}, {"TK_RPAREN", "r51"}, {"TK_SEMI", "r51"}, {"TK_SUB", "r51"}};
	 actTab[122] = {{"TK_LCURLY", "s28"}};
	 actTab[123] = {{"TK_RPAREN", "s129"}};
	 actTab[124] = {{"TK_ADD", "r26"}, {"TK_ASSIGN", "r26"}, {"TK_ASSIGN_DIFF", "r26"}, {"TK_ASSIGN_SUM", "r26"}, {"TK_CLASS", "r26"}, {"TK_COMMA", "r26"}, {"TK_DECREMENT", "r26"}, {"TK_DIV", "r26"}, {"TK_EOI", "r26"}, {"TK_EQU", "r26"}, {"TK_FN", "r26"}, {"TK_GT", "r26"}, {"TK_GTE", "r26"}, {"TK_ID", "r26"}, {"TK_IF", "r26"}, {"TK_INCREMENT", "r26"}, {"TK_LAMBDA", "r26"}, {"TK_LB", "r26"}, {"TK_LCURLY", "r26"}, {"TK_LET", "r26"}, {"TK_LPAREN", "r26"}, {"TK_LT", "r26"}, {"TK_LTE", "r26"}, {"TK_MOD", "r26"}, {"TK_MUL", "r26"}, {"TK_NEQ", "r26"}, {"TK_NEW", "r26"}, {"TK_NOT", "r26"}, {"TK_NUM", "r26"}, {"TK_PERIOD", "r26"}, {"TK_PRINT", "r26"}, {"TK_PRINTLN", "r26"}, {"TK_RB", "r26"}, {"TK_RCURLY", "r26"}, {"TK_RETURN", "r26"}, {"TK_RPAREN", "r26"}, {"TK_SEMI", "r26"}, {"TK_STRING", "r26"}, {"TK_SUB", "r26"}, {"TK_WHILE", "r26"}};
	 actTab[125] = {{"TK_LCURLY", "s28"}};
	 actTab[126] = {{"TK_ADD", "r70"}, {"TK_ASSIGN", "r70"}, {"TK_ASSIGN_DIFF", "r70"}, {"TK_ASSIGN_SUM", "r70"}, {"TK_COMMA", "r70"}, {"TK_DECREMENT", "r70"}, {"TK_DIV", "r70"}, {"TK_EQU", "r70"}, {"TK_GT", "r70"}, {"TK_GTE", "r70"}, {"TK_INCREMENT", "r70"}, {"TK_LB", "r70"}, {"TK_LPAREN", "r70"}, {"TK_LT", "r70"}, {"TK_LTE", "r70"}, {"TK_MOD", "r70"}, {"TK_MUL", "r70"}, {"TK_NEQ", "r70"}, {"TK_PERIOD", "r70"}, {"TK_RB", "r70"}, {"TK_RPAREN", "r70"}, {"TK_SEMI", "r70"}, {"TK_SUB", "r70"}};
	 actTab[127] = {{"TK_ADD", "r69"}, {"TK_ASSIGN", "r69"}, {"TK_ASSIGN_DIFF", "r69"}, {"TK_ASSIGN_SUM", "r69"}, {"TK_COMMA", "r69"}, {"TK_DECREMENT", "r69"}, {"TK_DIV", "r69"}, {"TK_EQU", "r69"}, {"TK_GT", "r69"}, {"TK_GTE", "r69"}, {"TK_INCREMENT", "r69"}, {"TK_LB", "r69"}, {"TK_LPAREN", "r69"}, {"TK_LT", "r69"}, {"TK_LTE", "r69"}, {"TK_MOD", "r69"}, {"TK_MUL", "r69"}, {"TK_NEQ", "r69"}, {"TK_PERIOD", "r69"}, {"TK_RB", "r69"}, {"TK_RPAREN", "r69"}, {"TK_SEMI", "r69"}, {"TK_SUB", "r69"}};
	 actTab[128] = {{"TK_ADD", "r23"}, {"TK_ASSIGN", "r23"}, {"TK_ASSIGN_DIFF", "r23"}, {"TK_ASSIGN_SUM", "r23"}, {"TK_CLASS", "r23"}, {"TK_COMMA", "r23"}, {"TK_DECREMENT", "r23"}, {"TK_DIV", "r23"}, {"TK_EOI", "r23"}, {"TK_EQU", "r23"}, {"TK_FN", "r23"}, {"TK_GT", "r23"}, {"TK_GTE", "r23"}, {"TK_ID", "r23"}, {"TK_IF", "r23"}, {"TK_INCREMENT", "r23"}, {"TK_LAMBDA", "r23"}, {"TK_LB", "r23"}, {"TK_LCURLY", "r23"}, {"TK_LET", "r23"}, {"TK_LPAREN", "r23"}, {"TK_LT", "r23"}, {"TK_LTE", "r23"}, {"TK_MOD", "r23"}, {"TK_MUL", "r23"}, {"TK_NEQ", "r23"}, {"TK_NEW", "r23"}, {"TK_NOT", "r23"}, {"TK_NUM", "r23"}, {"TK_PERIOD", "r23"}, {"TK_PRINT", "r23"}, {"TK_PRINTLN", "r23"}, {"TK_RB", "r23"}, {"TK_RCURLY", "r23"}, {"TK_RETURN", "r23"}, {"TK_RPAREN", "r23"}, {"TK_SEMI", "r23"}, {"TK_STRING", "r23"}, {"TK_SUB", "r23"}, {"TK_WHILE", "r23"}};
	 actTab[129] = {{"TK_LCURLY", "s28"}};
	 actTab[130] = {{"TK_ADD", "r24"}, {"TK_ASSIGN", "r24"}, {"TK_ASSIGN_DIFF", "r24"}, {"TK_ASSIGN_SUM", "r24"}, {"TK_CLASS", "r24"}, {"TK_COMMA", "r24"}, {"TK_DECREMENT", "r24"}, {"TK_DIV", "r24"}, {"TK_EOI", "r24"}, {"TK_EQU", "r24"}, {"TK_FN", "r24"}, {"TK_GT", "r24"}, {"TK_GTE", "r24"}, {"TK_ID", "r24"}, {"TK_IF", "r24"}, {"TK_INCREMENT", "r24"}, {"TK_LAMBDA", "r24"}, {"TK_LB", "r24"}, {"TK_LCURLY", "r24"}, {"TK_LET", "r24"}, {"TK_LPAREN", "r24"}, {"TK_LT", "r24"}, {"TK_LTE", "r24"}, {"TK_MOD", "r24"}, {"TK_MUL", "r24"}, {"TK_NEQ", "r24"}, {"TK_NEW", "r24"}, {"TK_NOT", "r24"}, {"TK_NUM", "r24"}, {"TK_PERIOD", "r24"}, {"TK_PRINT", "r24"}, {"TK_PRINTLN", "r24"}, {"TK_RB", "r24"}, {"TK_RCURLY", "r24"}, {"TK_RETURN", "r24"}, {"TK_RPAREN", "r24"}, {"TK_SEMI", "r24"}, {"TK_STRING", "r24"}, {"TK_SUB", "r24"}, {"TK_WHILE", "r24"}};
	 actTab[131] = {{"TK_ADD", "r25"}, {"TK_ASSIGN", "r25"}, {"TK_ASSIGN_DIFF", "r25"}, {"TK_ASSIGN_SUM", "r25"}, {"TK_CLASS", "r25"}, {"TK_COMMA", "r25"}, {"TK_DECREMENT", "r25"}, {"TK_DIV", "r25"}, {"TK_EOI", "r25"}, {"TK_EQU", "r25"}, {"TK_FN", "r25"}, {"TK_GT", "r25"}, {"TK_GTE", "r25"}, {"TK_ID", "r25"}, {"TK_IF", "r25"}, {"TK_INCREMENT", "r25"}, {"TK_LAMBDA", "r25"}, {"TK_LB", "r25"}, {"TK_LCURLY", "r25"}, {"TK_LET", "r25"}, {"TK_LPAREN", "r25"}, {"TK_LT", "r25"}, {"TK_LTE", "r25"}, {"TK_MOD", "r25"}, {"TK_MUL", "r25"}, {"TK_NEQ", "r25"}, {"TK_NEW", "r25"}, {"TK_NOT", "r25"}, {"TK_NUM", "r25"}, {"TK_PERIOD", "r25"}, {"TK_PRINT", "r25"}, {"TK_PRINTLN", "r25"}, {"TK_RB", "r25"}, {"TK_RCURLY", "r25"}, {"TK_RETURN", "r25"}, {"TK_RPAREN", "r25"}, {"TK_SEMI", "r25"}, {"TK_STRING", "r25"}, {"TK_SUB", "r25"}, {"TK_WHILE", "r25"}};
}
map<string, function<astnode*(vector<astnode*>&)>> actions;
void initActions() {
	 actions.insert({"binop",mkbinop});
	 actions.insert({"mkBlock",mkBlock});
	 actions.insert({"mkCall",mkCall});
	 actions.insert({"mkDotted",mkDotted});
	 actions.insert({"mkFunc",mkFunc});
	 actions.insert({"mkId",mkId});
	 actions.insert({"mkIf",mkIf});
	 actions.insert({"mkInstance",mkInstance});
	 actions.insert({"mkLambda",mkLambda});
	 actions.insert({"mkLet",mkLet});
	 actions.insert({"mkList",mkList});
	 actions.insert({"mkListCon",mkListCon});
	 actions.insert({"mkNum",mkNum});
	 actions.insert({"mkPrint",mkPrint});
	 actions.insert({"mkRet",mkRet});
	 actions.insert({"mkString",mkString});
	 actions.insert({"mkStruct",mkStruct});
	 actions.insert({"mkSubscript",mkSubscript});
	 actions.insert({"mkWhile",mkWhile});
	 actions.insert({"pass",pass});
	 actions.insert({"unary",unary});
}
